version: "3.9"
services:
  my_app:
    build: ./docker
    container_name: my_app

    ports:
      - "8080:8080"

    networks:
      - postgres

  postgres:
    image: postgres:13.3
    container_name: my_postgres

    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - .:/docker-entrypoint-initdb.d
      - testdb-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - postgres

volumes:
  testdb-data:


networks:
  postgres:
    driver: bridge
