HTTP_ADDRESS: "localhost:8080"
HTTP_READ_TIMEOUT: 5s
HTTP_WRITE_TIMEOUT: 5s
HTTP_IDLE_TIMEOUT: 10s

PG_HOST: "localhost"
PG_PORT: "7557"
PG_DBNAME: "vk"
PG_USER: "postgres"
PG_PASSWORD: "postgres"
PG_SSLMODE: "disable"